package solutions.design;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Random;
import java.util.Set;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

/**
 * Stateful contract tests for {@link Twitter_355} (LeetCode 355).
 *
 * <p>The expected feeds are either explicit contract examples or are generated by an independent
 * event-log model. In particular, the model does not use the production class's per-user list
 * representation or heap merge.</p>
 */
public class Twitter_355Test {
    private Twitter_355 test;

    @BeforeEach
    public void setUp() {
        test = new Twitter_355();
    }

    @Test
    public void officialExamplePostsFollowsAndUnfollows() {
        test.postTweet(1, 5);
        assertEquals(List.of(5), test.getNewsFeed(1));
        test.follow(1, 2);
        test.postTweet(2, 6);
        assertEquals(List.of(6, 5), test.getNewsFeed(1));
        test.unfollow(1, 2);
        assertEquals(List.of(5), test.getNewsFeed(1));
    }

    @Test
    public void unknownUserHasAnEmptyFeed() {
        assertEquals(List.of(), test.getNewsFeed(500));
        assertEquals(List.of(), test.getNewsFeed(500));
    }

    @Test
    public void followingUserWithoutTweetsHasAnEmptyFeed() {
        test.follow(1, 2);
        assertEquals(List.of(), test.getNewsFeed(1));
        assertEquals(List.of(), test.getNewsFeed(2));
    }

    @Test
    public void ownTweetsAreReturnedNewestFirst() {
        test.postTweet(1, 10);
        test.postTweet(1, 11);
        test.postTweet(1, 12);
        assertEquals(List.of(12, 11, 10), test.getNewsFeed(1));
    }

    @Test
    public void feedContainsAtMostTenTweets() {
        for (int tweetId = 0; tweetId < 12; tweetId++) {
            test.postTweet(1, tweetId);
        }
        assertEquals(List.of(11, 10, 9, 8, 7, 6, 5, 4, 3, 2), test.getNewsFeed(1));
    }

    @Test
    public void oldFolloweeTweetsBecomeVisibleAfterFollowing() {
        test.postTweet(2, 200);
        test.postTweet(2, 201);
        assertEquals(List.of(), test.getNewsFeed(1));
        test.follow(1, 2);
        assertEquals(List.of(201, 200), test.getNewsFeed(1));
    }

    @Test
    public void followeeTweetsAreMergedByGlobalRecency() {
        test.postTweet(2, 20);
        test.postTweet(3, 30);
        test.postTweet(1, 10);
        test.follow(1, 2);
        test.follow(1, 3);
        test.postTweet(2, 21);
        assertEquals(List.of(21, 10, 30, 20), test.getNewsFeed(1));
    }

    @Test
    public void interleavedUsersStillProduceOneGlobalOrder() {
        test.follow(1, 2);
        test.follow(1, 3);
        test.postTweet(2, 1);
        test.postTweet(3, 2);
        test.postTweet(2, 3);
        test.postTweet(3, 4);
        test.postTweet(2, 5);
        assertEquals(List.of(5, 4, 3, 2, 1), test.getNewsFeed(1));
    }

    @Test
    public void unfollowRemovesHistoricAndFutureFolloweeTweets() {
        test.follow(1, 2);
        test.postTweet(2, 20);
        test.postTweet(1, 10);
        assertEquals(List.of(10, 20), test.getNewsFeed(1));
        test.unfollow(1, 2);
        test.postTweet(2, 21);
        assertEquals(List.of(10), test.getNewsFeed(1));
    }

    @Test
    public void duplicateFollowIsIdempotent() {
        test.follow(1, 2);
        test.follow(1, 2);
        test.postTweet(2, 50);
        assertEquals(List.of(50), test.getNewsFeed(1));
    }

    @Test
    public void duplicateUnfollowIsIdempotent() {
        test.postTweet(1, 10);
        test.follow(1, 2);
        test.postTweet(2, 20);
        test.unfollow(1, 2);
        test.unfollow(1, 2);
        assertEquals(List.of(10), test.getNewsFeed(1));
    }

    @Test
    public void unfollowUnknownFolloweeIsAThreeWayNoOp() {
        test.postTweet(1, 10);
        test.unfollow(1, 99);
        assertEquals(List.of(10), test.getNewsFeed(1));
        test.unfollow(400, 99);
        assertEquals(List.of(), test.getNewsFeed(400));
    }

    @Test
    public void selfFollowDoesNotDuplicateOwnTweets() {
        test.postTweet(1, 7);
        test.follow(1, 1);
        test.follow(1, 1);
        assertEquals(List.of(7), test.getNewsFeed(1));
    }

    @Test
    public void implementationDefinedSelfUnfollowHidesOwnTweetsUntilRefollow() {
        test.postTweet(1, 7);
        test.unfollow(1, 1);
        assertEquals(List.of(), test.getNewsFeed(1));
        test.follow(1, 1);
        assertEquals(List.of(7), test.getNewsFeed(1));
    }

    @Test
    public void followAndUnfollowOrderControlsOnlyCurrentVisibility() {
        test.postTweet(2, 20);
        test.follow(1, 2);
        assertEquals(List.of(20), test.getNewsFeed(1));
        test.unfollow(1, 2);
        assertEquals(List.of(), test.getNewsFeed(1));
        test.follow(1, 2);
        assertEquals(List.of(20), test.getNewsFeed(1));
    }

    @Test
    public void separateUsersHaveIndependentFollowGraphsAndFeeds() {
        test.postTweet(2, 20);
        test.postTweet(3, 30);
        test.follow(1, 2);
        test.follow(4, 3);
        assertEquals(List.of(20), test.getNewsFeed(1));
        assertEquals(List.of(30), test.getNewsFeed(4));
        assertEquals(List.of(30), test.getNewsFeed(3));
    }

    @Test
    public void repeatedReadsDoNotConsumeTweetsOrChangeOrdering() {
        test.follow(1, 2);
        test.postTweet(1, 10);
        test.postTweet(2, 20);
        List<Integer> first = test.getNewsFeed(1);
        List<Integer> second = test.getNewsFeed(1);
        assertEquals(List.of(20, 10), first);
        assertEquals(first, second);
        test.postTweet(2, 21);
        assertEquals(List.of(21, 20, 10), test.getNewsFeed(1));
    }

    @Test
    public void boundaryUserAndTweetIdsAreSupported() {
        test.postTweet(1, 0);
        test.postTweet(500, 10_000);
        test.follow(1, 500);
        assertEquals(List.of(10_000, 0), test.getNewsFeed(1));
        assertEquals(List.of(10_000), test.getNewsFeed(500));
    }

    @Test
    public void maximumUserCountCanContributeToOneFeed() {
        for (int userId = 1; userId <= 500; userId++) {
            test.follow(500, userId);
        }
        for (int userId = 1; userId <= 500; userId++) {
            test.postTweet(userId, userId);
        }
        assertEquals(List.of(500, 499, 498, 497, 496, 495, 494, 493, 492, 491),
                test.getNewsFeed(500));
    }

    @Test
    public void maximumCallCountWithTenThousandUniqueTweets() {
        for (int tweetId = 0; tweetId < 10_000; tweetId++) {
            test.postTweet(1, tweetId);
        }
        for (int call = 0; call < 20_000; call++) {
            assertEquals(List.of(9_999, 9_998, 9_997, 9_996, 9_995, 9_994, 9_993, 9_992, 9_991, 9_990),
                    test.getNewsFeed(1));
        }
    }

    @Test
    public void manyFolloweesAreMergedAndCappedAtTen() {
        for (int userId = 2; userId <= 40; userId++) {
            test.follow(1, userId);
        }
        int tweetId = 0;
        for (int round = 0; round < 15; round++) {
            for (int userId = 2; userId <= 40; userId++) {
                test.postTweet(userId, tweetId++);
            }
        }
        List<Integer> expected = new ArrayList<>();
        for (int id = 584; id >= 575; id--) {
            expected.add(id);
        }
        assertEquals(expected, test.getNewsFeed(1));
    }

    @Test
    public void independentTwitterInstancesDoNotShareState() {
        Twitter_355 other = new Twitter_355();
        test.postTweet(1, 10);
        test.follow(1, 2);
        other.postTweet(1, 20);
        assertEquals(List.of(10), test.getNewsFeed(1));
        assertEquals(List.of(20), other.getNewsFeed(1));
    }

    @Test
    public void eventLogOracleChecksSeededMixedStateTransitions() {
        ReferenceTwitter reference = new ReferenceTwitter();
        Random random = new Random(355L);
        int nextTweetId = 0;

        for (int operation = 0; operation < 2_000; operation++) {
            int userId = 1 + random.nextInt(31);
            int operationType = random.nextInt(4);
            if (operationType == 0 && nextTweetId < 10_000) {
                test.postTweet(userId, nextTweetId);
                reference.postTweet(userId, nextTweetId);
                nextTweetId++;
            } else if (operationType == 1) {
                int followeeId = 1 + random.nextInt(31);
                test.follow(userId, followeeId);
                reference.follow(userId, followeeId);
            } else if (operationType == 2) {
                int followeeId = 1 + random.nextInt(31);
                test.unfollow(userId, followeeId);
                reference.unfollow(userId, followeeId);
            } else {
                assertEquals(reference.getNewsFeed(userId), test.getNewsFeed(userId),
                        "mismatch after operation " + operation);
            }
        }

        for (int userId = 1; userId <= 31; userId++) {
            assertEquals(reference.getNewsFeed(userId), test.getNewsFeed(userId),
                    "final mismatch for user " + userId);
        }
    }

    @Test
    public void eventLogOracleHandlesAlternatingFollowAndTweetWaves() {
        ReferenceTwitter reference = new ReferenceTwitter();
        for (int round = 0; round < 50; round++) {
            int follower = 1 + round % 5;
            int followee = 6 + round % 5;
            test.follow(follower, followee);
            reference.follow(follower, followee);
            test.postTweet(followee, 1_000 + round);
            reference.postTweet(followee, 1_000 + round);
            test.postTweet(follower, 2_000 + round);
            reference.postTweet(follower, 2_000 + round);
            if (round % 3 == 2) {
                test.unfollow(follower, followee);
                reference.unfollow(follower, followee);
            }
            for (int userId = 1; userId <= 10; userId++) {
                assertEquals(reference.getNewsFeed(userId), test.getNewsFeed(userId));
            }
        }
    }

    @Test
    public void resultListsAreIndependentSnapshots() {
        test.postTweet(1, 1);
        test.postTweet(1, 2);
        List<Integer> first = test.getNewsFeed(1);
        first.clear();
        assertEquals(List.of(2, 1), test.getNewsFeed(1));
    }

    /** Independent, intentionally simple event-log model for the Twitter contract. */
    private static final class ReferenceTwitter {
        private final Map<Integer, Set<Integer>> following = new HashMap<>();
        private final Map<Integer, List<ReferenceTweet>> tweets = new HashMap<>();
        private int timestamp;

        private void ensureUser(int userId) {
            following.computeIfAbsent(userId, ignored -> {
                Set<Integer> self = new HashSet<>();
                self.add(userId);
                return self;
            });
            tweets.computeIfAbsent(userId, ignored -> new ArrayList<>());
        }

        private void postTweet(int userId, int tweetId) {
            ensureUser(userId);
            tweets.get(userId).add(new ReferenceTweet(tweetId, timestamp++));
        }

        private void follow(int followerId, int followeeId) {
            ensureUser(followerId);
            following.get(followerId).add(followeeId);
        }

        private void unfollow(int followerId, int followeeId) {
            ensureUser(followerId);
            following.get(followerId).remove(followeeId);
        }

        private List<Integer> getNewsFeed(int userId) {
            Set<Integer> visibleUsers = following.get(userId);
            if (visibleUsers == null) {
                return List.of();
            }
            List<ReferenceTweet> visibleTweets = new ArrayList<>();
            for (int visibleUser : visibleUsers) {
                List<ReferenceTweet> userTweets = tweets.get(visibleUser);
                if (userTweets != null) {
                    visibleTweets.addAll(userTweets);
                }
            }
            visibleTweets.sort(Comparator.comparingInt((ReferenceTweet tweet) -> tweet.timestamp)
                    .reversed());
            List<Integer> result = new ArrayList<>();
            for (int index = 0; index < Math.min(10, visibleTweets.size()); index++) {
                result.add(visibleTweets.get(index).tweetId);
            }
            return result;
        }
    }

    private record ReferenceTweet(int tweetId, int timestamp) {
    }
}
